IPsec RA VPN: fix connection-id parsing
Connection client/server profiles hyphen broke the weak
regex and resulted in python tracebacks for show vpn ipsec/ike sa
commands:

Traceback (most recent call last):
  File "/opt/vyatta/sbin/vyatta-op-vpn-ipsec-vici", line 766, in <module>
    show_ike_sa(mode=Mode.BRIEF, vrf=vrf)
  File "/opt/vyatta/sbin/vyatta-op-vpn-ipsec-vici", line 564, in show_ike_sa
    show_ipsec_sa(vrf=vrf, show_ike=True)
  File "/opt/vyatta/sbin/vyatta-op-vpn-ipsec-vici", line 556, in show_ipsec_sa
    dump_ike_sa(conn_id, ike_sa, mode)
  File "/opt/vyatta/sbin/vyatta-op-vpn-ipsec-vici", line 317, in dump_ike_sa
    description = profile_config.get('description')
AttributeError: 'NoneType' object has no attribute 'get'

VRVDR-49839