vyatta-ike-sa-daemon: prevent exception if current_ike_cfg is undefined
Traceback (most recent call last):
  File "/opt/vyatta/sbin/vyatta-ike-sa-daemon", line 2091, in _worker_run
    job.run(vs)
  File "/opt/vyatta/sbin/vyatta-ike-sa-daemon", line 1165, in run
    return self._run()
  File "/opt/vyatta/sbin/vyatta-ike-sa-daemon", line 1244, in _run
    if conn.current_ike_cfg.conn_id is None:
AttributeError: 'NoneType' object has no attribute 'conn_id'